# general setting
name: dt4d
backend: dp # DataParallel
type: FAPModel
num_gpu: 1 # 
gpu_idx: 7 # 
manual_seed: 1234
non-isometric: True
partial: false

# path
path:
  resume_state: ~

# datasets
datasets:
  train_dataset1:
    name: DT4DIntraTrain
    type: PairDT4DDataset
    phase: train
    data_root: ../data/DT4D_r/
    inter_class: False
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: False
    return_dist: False
  train_dataset2:
    name: DT4DInterTrain
    type: PairDT4DDataset
    phase: train
    data_root: ../data/DT4D_r/
    inter_class: True
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: False
    return_dist: False
  test_dataset:
    name: DT4DTest
    type: PairDT4DDataset
    phase: test
    data_root: ../data/DT4D_r/
    inter_class: True
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: True
    return_dist: True
  # setting for train dataset
  batch_size: 1
  num_worker: 16

# network setting
networks:
  #1 Unsupervised LRSSM
  feature_extractor:
    type: DiffusionNet
    in_channels: 128
    out_channels: 256
    cache_dir: ../data/DT4D_r/diffusion
    input_type: wks
  fmap_net:
    type: RegularizedFMNet
    bidirectional: true
  permutation:
    type: Similarity
    tau: 0.07 #0.07

  # #2 learning filter
  conv:
    type: Learned_Fliters
    Poly_Type: JacobiConv
    orders: 8 
    alpha: 1.0 
    learnable_bases: True
    learnable_alphas: True
    normalized_bases: True
    a: 1.0
    b: 1.0
  
  # #3 combination
  comb:
    type: Combination
    orders_basis: 8 
    output_channels: 6

# training setting
train:
  optims: 
    feature_extractor:
      type: Adam
      lr: 1.0e-3
    conv:
      type: Adam
      lr: 1.0e-3
    comb:
      type: Adam
      lr: 1.0e-3
  schedulers:
    feature_extractor:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 10 
    conv:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 10 
    comb:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 10 

  losses:
    surfmnet_loss:
      type: SURFMNetLoss
      w_bij: 1.0
      w_orth: 1.0
      w_lap: 0.0
      bidirectional: true #
    align_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 1.0
    dirichlet_loss:
      type: DirichletLoss
      loss_weight: 5.0   #

# validation setting
val:
  val_freq: 4000
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

# log setting
logger:
  print_freq: 100
  save_checkpoint_freq: 4000
